version: "3.4"

services:
  mysql:
    image: mysql:5.7
    container_name: bitcoin_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  app:
    container_name: bitcoin_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_KEY:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD:
    ports:
      - "8080:80"
    command: ["./init.sh"]
    depends_on:
      - mysql
  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    command: ["./fe.sh"]
    tty: true