export const TRADES_GET_REQUEST = 'TRADES_GET_REQUEST';
export const TRADES_GET_SUCCESS = 'TRADES_GET_SUCCESS';
export const TRADES_GET_FAILURE = 'TRADES_GET_FAILURE';

export const ADD_CURRENT_TRADE = 'ADD_CURRENT_TRADE';